version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
#      - ./db:/app/db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway" 